# Datasource Settings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console Settings
spring.h2.console.enabled=true

# SQL Initialization Settings
spring.sql.init.mode=always

# Flyway Settings
spring.flyway.enabled=false

# do not run docker for local config
spring.docker.compose.enabled=false