# Datasource Settings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false

# SQL Initialization Settings
spring.sql.init.mode=never

# H2 Console Settings
spring.h2.console.enabled=true

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

# do not run docker for local config
spring.docker.compose.enabled=false

# TODO: Get rid of this unsecure, not recommended authentication method asap ;)
## In Memory User Details (avoid hardcoded credentials in code to avoid flagging sonar)
local.admin.username=alice_admin
local.admin.password=password
local.admin.role=ADMIN

local.user.username=john_user
local.user.password=password
local.user.role=USER

### SQL Generation Settings to create the database schema ###
## Enable script generation
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql
#
## Match the dialect to your production database (e.g., PostgreSQL, MySQL)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect