# Datasource Settings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false

# H2 Console Settings
spring.h2.console.enabled=true

# SQL Initialization Settings
spring.sql.init.mode=never

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.clean-disabled=false


# do not run docker for local config
spring.docker.compose.enabled=false


### SQL Generation Settings to create the database schema ###
## Enable script generation
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql
#
## Match the dialect to your production database (e.g., PostgreSQL, MySQL)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect