# Datasource Settings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false

# SQL Initialization Settings
spring.sql.init.mode=never

# H2 Console Settings
spring.h2.console.enabled=true

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

# do not run docker for local config
spring.docker.compose.enabled=false

auth0.domain=${AUTH0_DOMAIN}
auth0.audience=${AUTH0_AUDIENCE}