# Datasource Settings
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# SQL Initialization Settings
spring.sql.init.mode=never

# Flyway Settings
spring.flyway.enabled=true

# Server Settings
server.port=${PORT:8080}