logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
spring.application.name=eventhub
spring.jackson.time-zone=UTC
spring.profiles.default=local
server.port=8080

spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

spring.web.error.path=/error
spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
